# This file configures ArgoCD to be installed in High Availablity mode.
# See details at https://github.com/argoproj/argo-helm/tree/main/charts/argo-cd#high-availability

redis-ha:
  enabled: true

controller:
  replicas: 1

server:
  autoscaling:
    enabled: true
    minReplicas: 2

repoServer:
  autoscaling:
    enabled: true
    minReplicas: 2

applicationSet:
  replicas: 2